"""Feature-level variogram-matched spatial null via log-space multiplicative
sender/receiver decomposition.

Model
-----
For each CCI feature ``f`` (a fixed ``(LR pair, ct_sender, ct_receiver)``
triplet) the real feature value at edge ``e = (r_s, r_r)`` is
approximated by the first-order log-linear model

    log x_f(e) ~= logL_f(r_s) + logR_f(r_r) - log_baseline_f + residual

where ``logL_f(r)`` is the mean log-feature over sender-edges out of
``r`` (excluding self-loops) and ``logR_f(r)`` is the corresponding
receiver-edge marginal. In linear scale this is equivalent to
``x_f(e) ~= L(r_s) * R(r_r) / baseline_f`` -- multiplicative, matching
NeuronChat's native ``f(ligand) * g(receptor)`` form.

Null surrogates are generated by brainSMASH'ing ``logL_f`` and
``logR_f`` on the unique-spatial-node grid, redistributing back to
ABC regions, and reconstructing
``log X_null[s, e, f] = logL_surr[s, f, r_s] + logR_surr[s, f, r_r]
- log_baseline_f``. Exponentiating gives a non-negative null X matrix
with variogram-matched per-region marginals.

Design
------
- **Joint L/R scramble**: the same brainSMASH seed is applied to
  ``logL_f`` and ``logR_f`` within each ``(surrogate, feature)``.
  Preserves within-feature correlation between a region's sender and
  receiver strengths; tighter null than independent scramble.
- **Self-loops excluded** from both ``logL`` and ``logR`` aggregations.
- **Epsilon floor** before log: default 1e-3 (~q01_positive / 4 on the
  real expanded-ABC X).
- **First-order log-linear model**: any non-separable region-pair
  interaction term is intentionally ignored -- that is the spatial-AC
  null hypothesis.

This module is numerically pure; the driver at
``src/pipeline/connectivity_prediction/feature_level_null.py`` wires the output into
per-target LOBO via the ``lobo_only`` stage of ``spatial_null.py``.
"""

from __future__ import annotations

import logging
from typing import Dict, Mapping, Sequence, Tuple

import numpy as np
import pandas as pd
from joblib import Parallel, delayed
from tqdm.auto import tqdm

from clrc.core.parallel import tqdm_joblib
from clrc.spatial.atlas import (
    aggregate_abc_map_to_unique,
)
from clrc.spatial.nulls import generate_brainsmash_surrogates

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
#  Sender / receiver log-marginal decomposition
# ---------------------------------------------------------------------------


_SENDER_COL_ALIASES = ("sender_region", "src_region")
_RECEIVER_COL_ALIASES = ("receiver_region", "tgt_region")


def _pick_edge_column(edge_table: pd.DataFrame, aliases: Sequence[str]) -> str:
    for c in aliases:
        if c in edge_table.columns:
            return c
    raise ValueError(
        f"edge_table has no column matching any of {aliases}. "
        f"Columns present: {list(edge_table.columns)}."
    )


def compute_sender_receiver_log_maps(
    X: np.ndarray,
    edge_table: pd.DataFrame,
    regions: Sequence[str],
    *,
    eps: float = 1e-3,
    exclude_self_loops: bool = True,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Decompose each feature into per-region sender + receiver log-marginals.

    For each feature ``f`` and each region ``r``:

    - ``logL[f, r]`` = mean over non-self edges with sender_region == r
      of ``log(max(X[e, f], eps))``.
    - ``logR[f, r]`` = mean over non-self edges with receiver_region == r
      of ``log(max(X[e, f], eps))``.

    ``log_baseline[f]`` = mean over non-self edges of
    ``log(max(X[e, f], eps))`` -- the grand mean used to avoid
    double-counting in the additive reconstruction.

    Parameters
    ----------
    X : (n_edges, n_features) array
        Real CCI feature matrix.
    edge_table : DataFrame
        Must contain ``sender_region`` and ``receiver_region`` columns
        whose values are in ``regions``. Row order must match ``X``.
    regions : sequence of str
        Canonical region ordering; output array columns align to this.
    eps : float, default 1e-3
        Lower-bound floor applied before the log transform. Values
        ``X[e, f] < eps`` are treated as ``eps``.
    exclude_self_loops : bool, default True
        If ``True``, edges where ``sender_region == receiver_region``
        are dropped from the aggregation.

    Returns
    -------
    logL : (n_features, n_regions) array
    logR : (n_features, n_regions) array
    log_baseline : (n_features,) array

    Raises
    ------
    ValueError
        If X / edge_table sizes disagree, if ``eps <= 0``, or if a
        region in ``regions`` never appears as a non-self sender (or
        receiver) -- the corresponding row is filled with
        ``log_baseline[f]`` (see Notes) and we warn.

    Notes
    -----
    Missing-region fallback: a region with zero non-self edges (rare
    edge case, e.g. a region that only connects to itself) gets its
    log-marginal set to ``log_baseline[f]`` per feature. This keeps
    downstream reconstruction well-defined.
    """
    if eps <= 0:
        raise ValueError(f"eps must be > 0, got {eps!r}.")
    X = np.asarray(X)
    if X.ndim != 2:
        raise ValueError(f"X must be 2D (n_edges, n_features), got shape {X.shape}.")
    n_edges, n_features = X.shape
    if len(edge_table) != n_edges:
        raise ValueError(
            f"edge_table has {len(edge_table)} rows but X has {n_edges}."
        )
    sender_col = _pick_edge_column(edge_table, _SENDER_COL_ALIASES)
    receiver_col = _pick_edge_column(edge_table, _RECEIVER_COL_ALIASES)

    regions = list(regions)
    n_regions = len(regions)
    region_to_idx: Dict[str, int] = {r: i for i, r in enumerate(regions)}

    sender_idx = edge_table[sender_col].map(region_to_idx).to_numpy()
    receiver_idx = edge_table[receiver_col].map(region_to_idx).to_numpy()
    if np.any(pd.isna(sender_idx)) or np.any(pd.isna(receiver_idx)):
        bad_s = set(edge_table[sender_col].unique()) - set(regions)
        bad_r = set(edge_table[receiver_col].unique()) - set(regions)
        raise ValueError(
            f"edge_table has region names not in `regions`. "
            f"sender-side missing: {sorted(bad_s)[:5]}; "
            f"receiver-side missing: {sorted(bad_r)[:5]}."
        )
    sender_idx = sender_idx.astype(np.int64)
    receiver_idx = receiver_idx.astype(np.int64)

    non_self = (
        (sender_idx != receiver_idx) if exclude_self_loops
        else np.ones(n_edges, dtype=bool)
    )
    n_non_self = int(non_self.sum())
    if n_non_self == 0:
        raise ValueError(
            "After self-loop exclusion, no edges remain. Set "
            "exclude_self_loops=False or check edge_table."
        )

    logX = np.log(np.maximum(X, eps))  # (n_edges, n_features)
    logX_sub = logX[non_self]
    s_sub = sender_idx[non_self]
    r_sub = receiver_idx[non_self]

    # Baseline: per-feature mean over all retained edges.
    log_baseline = logX_sub.mean(axis=0)  # (n_features,)

    # Per-region marginals. np.add.at is the idiomatic per-index accumulator.
    logL = np.zeros((n_features, n_regions), dtype=np.float64)
    logR = np.zeros((n_features, n_regions), dtype=np.float64)
    count_L = np.zeros(n_regions, dtype=np.int64)
    count_R = np.zeros(n_regions, dtype=np.int64)

    # logL[f, r] = sum over edges-with-sender=r of logX[e, f], then / count
    np.add.at(logL.T, s_sub, logX_sub)   # transpose so we accumulate along axis 0 = region
    np.add.at(logR.T, r_sub, logX_sub)
    np.add.at(count_L, s_sub, 1)
    np.add.at(count_R, r_sub, 1)

    # Fill regions with zero edges using log_baseline per feature.
    missing_L = count_L == 0
    missing_R = count_R == 0
    if missing_L.any():
        missing_names = [regions[i] for i in np.where(missing_L)[0]]
        logger.warning(
            "compute_sender_receiver_log_maps: %d regions have no non-self "
            "sender-edges; filling logL with per-feature baseline (%s).",
            int(missing_L.sum()), missing_names[:5],
        )
    if missing_R.any():
        missing_names = [regions[i] for i in np.where(missing_R)[0]]
        logger.warning(
            "compute_sender_receiver_log_maps: %d regions have no non-self "
            "receiver-edges; filling logR with per-feature baseline (%s).",
            int(missing_R.sum()), missing_names[:5],
        )

    # Divide where count > 0.
    with np.errstate(invalid="ignore", divide="ignore"):
        logL = np.where(
            (count_L > 0)[np.newaxis, :],
            logL / np.where(count_L == 0, 1, count_L)[np.newaxis, :],
            log_baseline[:, np.newaxis],
        )
        logR = np.where(
            (count_R > 0)[np.newaxis, :],
            logR / np.where(count_R == 0, 1, count_R)[np.newaxis, :],
            log_baseline[:, np.newaxis],
        )

    logger.info(
        "compute_sender_receiver_log_maps: X shape=%s, n_non_self=%d, "
        "eps=%.3g. logL range=[%.3g, %.3g] logR range=[%.3g, %.3g] "
        "log_baseline range=[%.3g, %.3g]",
        X.shape, n_non_self, eps,
        float(logL.min()), float(logL.max()),
        float(logR.min()), float(logR.max()),
        float(log_baseline.min()), float(log_baseline.max()),
    )
    return logL, logR, log_baseline


# ---------------------------------------------------------------------------
#  brainSMASH on per-feature log-marginals (joint seed)
# ---------------------------------------------------------------------------


def _surrogate_one_feature(
    f_idx: int,
    logL_f: np.ndarray,
    logR_f: np.ndarray,
    distance_86: np.ndarray,
    unique_nodes_df: pd.DataFrame,
    voxel_counts: np.ndarray,
    abc_to_allen_idx: Mapping[str, Sequence[int]],
    abc_regions_ordering: Sequence[str],
    n_surrogates: int,
    seed_base: int,
    joint: bool,
) -> Tuple[int, np.ndarray, np.ndarray]:
    """Generate variogram-matched surrogates for one feature's L/R log-marginals.

    Self-contained per-feature unit so :func:`surrogate_log_maps_variogram_matched`
    can dispatch this across joblib workers. Returns ``(f_idx, L_abc, R_abc)``
    where each ``*_abc`` is shape ``(n_surrogates, 101)``.

    Inner brainSMASH calls run with ``n_jobs=1`` because the outer loop is
    already parallelized at the feature level; nesting outer-joblib inside
    inner-brainSMASH-joblib oversubscribes cores.
    """
    L_uniq = aggregate_abc_map_to_unique(
        logL_f, unique_nodes_df, voxel_counts,
        abc_to_allen_idx, abc_regions_ordering,
    )
    R_uniq = aggregate_abc_map_to_unique(
        logR_f, unique_nodes_df, voxel_counts,
        abc_to_allen_idx, abc_regions_ordering,
    )

    seed_L = int(seed_base) + 2 * int(f_idx)
    seed_R = seed_L if joint else seed_L + 1

    # resample=True applies the empirical CDF of the input log-marginal
    # to the surrogate outputs, preventing brainSMASH's variogram-matched
    # Gaussian smoothing from extrapolating well beyond the input range.
    # Without this, exp(logL_surr + logR_surr) blows up by orders of
    # magnitude on any tail-extrapolated region.
    L_surr_uniq = generate_brainsmash_surrogates(
        map_values=L_uniq,
        distance_matrix=distance_86,
        n_surrogates=int(n_surrogates),
        seed=seed_L,
        n_jobs=1,
        resample=True,
    )  # (n_surrogates, 86)
    R_surr_uniq = generate_brainsmash_surrogates(
        map_values=R_uniq,
        distance_matrix=distance_86,
        n_surrogates=int(n_surrogates),
        seed=seed_R,
        n_jobs=1,
        resample=True,
    )

    # Vectorized redistribute: build the (n_surrogates, 101) ABC arrays
    # in a single broadcast per side instead of a Python loop over
    # surrogates. redistribute_surrogate_to_abc maps each ABC region to
    # its unique-group index; the membership map is the same for every
    # surrogate, so we look up once and gather.
    L_surr_abc = _redistribute_batched(
        L_surr_uniq, unique_nodes_df, abc_regions_ordering,
    )
    R_surr_abc = _redistribute_batched(
        R_surr_uniq, unique_nodes_df, abc_regions_ordering,
    )
    return f_idx, L_surr_abc, R_surr_abc


def _redistribute_batched(
    surrogates_uniq: np.ndarray,
    unique_nodes_df: pd.DataFrame,
    abc_regions_ordering: Sequence[str],
) -> np.ndarray:
    """Vectorized form of :func:`redistribute_surrogate_to_abc` over surrogates.

    Parameters
    ----------
    surrogates_uniq : (n_surrogates, n_unique_groups) array
    unique_nodes_df, abc_regions_ordering
        Same as the scalar redistribute helper.

    Returns
    -------
    (n_surrogates, n_abc_regions) array
    """
    # Build the per-ABC-region group_id lookup once. unique_nodes_df has
    # one row per group with an `abc_regions` list; invert that mapping.
    abc_to_group: Dict[str, int] = {}
    for row in unique_nodes_df.itertuples(index=False):
        gid = int(row.group_id)
        for abc_name in row.abc_regions:
            abc_to_group[abc_name] = gid
    group_per_abc = np.array(
        [abc_to_group[a] for a in abc_regions_ordering], dtype=np.int64
    )
    # surrogates_uniq[:, group_per_abc] gathers into (n_surrogates, n_abc).
    return surrogates_uniq[:, group_per_abc]


def surrogate_log_maps_variogram_matched(
    logL: np.ndarray,
    logR: np.ndarray,
    distance_86: np.ndarray,
    unique_nodes_df: pd.DataFrame,
    voxel_counts: np.ndarray,
    abc_to_allen_idx: Mapping[str, Sequence[int]],
    abc_regions_ordering: Sequence[str],
    *,
    n_surrogates: int,
    seed_base: int = 0,
    joint: bool = True,
    n_jobs: int = 1,
) -> Tuple[np.ndarray, np.ndarray]:
    """Generate variogram-matched log-marginal surrogates per feature.

    For each feature ``f``:

    1. Aggregate ``logL[f]`` and ``logR[f]`` from 101 ABC regions to
       86 unique spatial groups (voxel-weighted mean).
    2. Generate ``n_surrogates`` brainSMASH surrogates for each
       aggregated map on the 86x86 distance matrix.
    3. Redistribute each 86-length surrogate back to 101 ABC regions
       (broadcast within constituent-set groups).

    If ``joint=True``, the brainSMASH seed for feature ``f``'s
    receiver surrogate equals the seed for its sender surrogate --
    the same random permutation is applied to both within each
    ``(surrogate, feature)``. This preserves the within-feature
    correlation between sender and receiver spatial patterns.

    The per-feature work is dispatched across ``joblib.Parallel(n_jobs)``;
    each feature is independent (different brainSMASH seed and
    independent input map). Inner brainSMASH calls run single-threaded
    to avoid nested-parallelism oversubscription.

    Parameters
    ----------
    logL, logR : (n_features, 101) arrays
        From :func:`compute_sender_receiver_log_maps`.
    distance_86 : (86, 86) array
        Unique-spatial-group distance matrix.
    unique_nodes_df, voxel_counts, abc_to_allen_idx,
    abc_regions_ordering
        Same arguments passed to
        :func:`clrc.spatial.atlas.aggregate_abc_map_to_unique` /
        :func:`clrc.spatial.atlas.redistribute_surrogate_to_abc`.
    n_surrogates : int
        Number of surrogate draws per feature.
    seed_base : int, default 0
        Base seed. Per-feature seed is ``seed_base + f_idx * 2`` for
        logL, plus an offset of ``+1`` for logR when ``joint=False``;
        when ``joint=True`` the same seed is used for logR as logL.
        Per-feature deterministic seeding means parallel and serial
        runs produce bit-equal output.
    joint : bool, default True
        If True, same brainSMASH seed for sender and receiver within
        each feature (locked design choice).
    n_jobs : int, default 1
        joblib worker count for the per-feature outer loop. ``1``
        means serial.

    Returns
    -------
    logL_surr : (n_surrogates, n_features, 101) array
    logR_surr : (n_surrogates, n_features, 101) array
    """
    logL = np.asarray(logL, dtype=np.float64)
    logR = np.asarray(logR, dtype=np.float64)
    if logL.shape != logR.shape:
        raise ValueError(
            f"logL shape {logL.shape} != logR shape {logR.shape}."
        )
    n_features, n_abc = logL.shape
    if n_abc != len(abc_regions_ordering):
        raise ValueError(
            f"logL has {n_abc} region columns but "
            f"abc_regions_ordering has {len(abc_regions_ordering)}."
        )
    distance_86 = np.asarray(distance_86, dtype=np.float64)
    if distance_86.ndim != 2 or distance_86.shape[0] != distance_86.shape[1]:
        raise ValueError(
            f"distance_86 must be square; got shape {distance_86.shape}."
        )
    n_unique = distance_86.shape[0]

    voxel_counts = np.asarray(voxel_counts, dtype=np.float64)

    logL_surr = np.empty((n_surrogates, n_features, n_abc), dtype=np.float64)
    logR_surr = np.empty((n_surrogates, n_features, n_abc), dtype=np.float64)

    logger.info(
        "surrogate_log_maps: dispatching %d features across n_jobs=%d "
        "(n_unique=%d, n_surrogates=%d, joint=%s).",
        n_features, n_jobs, n_unique, int(n_surrogates), joint,
    )
    tasks = (
        delayed(_surrogate_one_feature)(
            f_idx,
            logL[f_idx],
            logR[f_idx],
            distance_86,
            unique_nodes_df,
            voxel_counts,
            abc_to_allen_idx,
            abc_regions_ordering,
            int(n_surrogates),
            int(seed_base),
            bool(joint),
        )
        for f_idx in range(n_features)
    )
    with tqdm_joblib(tqdm(total=n_features, desc="surrogate features", unit="feat")):
        results = Parallel(n_jobs=n_jobs, backend="loky")(tasks)

    for f_idx, L_abc, R_abc in results:
        logL_surr[:, f_idx, :] = L_abc
        logR_surr[:, f_idx, :] = R_abc

    return logL_surr, logR_surr


# ---------------------------------------------------------------------------
#  Null X reconstruction (per surrogate)
# ---------------------------------------------------------------------------


def reconstruct_null_X_surrogate(
    logL_surr_s: np.ndarray,
    logR_surr_s: np.ndarray,
    log_baseline: np.ndarray,
    edge_table: pd.DataFrame,
    regions: Sequence[str],
) -> np.ndarray:
    """Reconstruct the null X matrix for one surrogate ``s``.

    For each edge ``e = (r_s, r_r)`` and each feature ``f``:

        X_null[e, f] = exp(logL_surr[f, r_s] + logR_surr[f, r_r]
                           - log_baseline[f])

    Parameters
    ----------
    logL_surr_s, logR_surr_s : (n_features, n_regions) arrays
        One surrogate's log-marginals, from
        :func:`surrogate_log_maps_variogram_matched`.
    log_baseline : (n_features,) array
    edge_table, regions
        Same as :func:`compute_sender_receiver_log_maps`.

    Returns
    -------
    X_null : (n_edges, n_features) array, non-negative.
    """
    logL_surr_s = np.asarray(logL_surr_s, dtype=np.float64)
    logR_surr_s = np.asarray(logR_surr_s, dtype=np.float64)
    log_baseline = np.asarray(log_baseline, dtype=np.float64).ravel()
    regions = list(regions)
    region_to_idx = {r: i for i, r in enumerate(regions)}
    sender_col = _pick_edge_column(edge_table, _SENDER_COL_ALIASES)
    receiver_col = _pick_edge_column(edge_table, _RECEIVER_COL_ALIASES)
    sender_idx = edge_table[sender_col].map(region_to_idx).to_numpy(dtype=np.int64)
    receiver_idx = edge_table[receiver_col].map(region_to_idx).to_numpy(dtype=np.int64)

    # log_X_null[e, f] = logL[f, r_s] + logR[f, r_r] - log_baseline[f]
    # Transpose so rows are features, columns are edges; then transpose back.
    log_X_null = (
        logL_surr_s[:, sender_idx]       # (n_features, n_edges)
        + logR_surr_s[:, receiver_idx]   # (n_features, n_edges)
        - log_baseline[:, np.newaxis]
    ).T  # (n_edges, n_features)
    X_null = np.exp(log_X_null)
    return X_null


__all__ = [
    "compute_sender_receiver_log_maps",
    "surrogate_log_maps_variogram_matched",
    "reconstruct_null_X_surrogate",
]
